# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: erc20indexer
description: ERC-20 indexer
networks:
  - id: 324
    start_block: 24799912
    contracts:
      - name: AccountFactoryV2
        abi_file_path: abis/AccountFactoryV2.json
        handler: src/FactoryHandlers.ts
        address:
          - 0x2B196aaB35184aa539E3D8360258CAF8d8309Ebc
        events:
          - event: "ClaveAccountDeployed(address indexed accountAddress)"
      - name: ERC20
        handler: src/ERC20Handlers.ts
        events:
          - event: "Transfer(address indexed from, address indexed to, uint256 value)"
rollback_on_reorg: false
